#!/usr/bin/env node
/**
 * Reads the generated Tailwind CSS and writes it as a TypeScript module
 * so it can be bundled and injected into the web DOM by _layout.tsx.
 * Run via: npm run tw:build
 */
const fs = require('fs');
const path = require('path');

const cssPath = path.join(__dirname, '../public/tailwind.css');
const outPath = path.join(__dirname, '../lib/injectWebCSS.web.ts');

const css = fs.readFileSync(cssPath, 'utf8');
const escaped = JSON.stringify(css);

const NATIVE_FEEL_CSS = `
/* Native-feel PWA: touch, scroll, selection (appended before Tailwind) */
html, body {
  overscroll-behavior: none;
}
* {
  -webkit-tap-highlight-color: transparent;
}
button, a, [role="button"], summary, label, input[type="submit"], input[type="button"] {
  touch-action: manipulation;
  -webkit-touch-callout: none;
}
input, textarea, select, [contenteditable="true"] {
  touch-action: manipulation;
  -webkit-touch-callout: default;
  user-select: text;
  -webkit-user-select: text;
}
body {
  user-select: none;
  -webkit-user-select: none;
}
#root, #root * {
  overscroll-behavior-y: contain;
}
#root [style*="overflow"] {
  -webkit-overflow-scrolling: touch;
}
`;

const ANIMATIONS = `
@keyframes liquidFlow {
  0%   { background-position: 200% center; }
  100% { background-position: -200% center; }
}
`;

const content = `// AUTO-GENERATED by \`npm run tw:build\` — do not edit manually.
// Contains Tailwind CSS inlined for web injection via useEffect.

let injected = false;

const ANIMATIONS = ${JSON.stringify(ANIMATIONS)};
const NATIVE_FEEL_CSS = ${JSON.stringify(NATIVE_FEEL_CSS)};

export function injectWebCSS(): void {
  if (typeof document === 'undefined' || injected) return;
  injected = true;
  const existing = document.getElementById('app-tailwind');
  if (existing) return;
  const style = document.createElement('style');
  style.id = 'app-tailwind';
  style.textContent = ANIMATIONS + NATIVE_FEEL_CSS + CSS;
  document.head.appendChild(style);
}

const CSS = ${escaped};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`✅ injectWebCSS.web.ts updated (${Math.round(css.length / 1024)}KB CSS inlined)`);
